export const getGraphFakeData2 = {
  entityList: [
    {
      tin: "HARRYPOTTER",
      tinType: "0",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "Harry Potter",
      type: "0",
      flags: "0010101",
      isInitial: true,
      entityType: null,
      mft: 65,
      tpi: 0,
      assets: "318932700",
      linkTin: null,
      groupNode: false,
      positiveFlow: "150500",
      negativeFlow: null,
    },
    {
      tin: "RONWEASLEY",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "RON WEASLEY",
      type: "1",
      flags: "0000000",
      isInitial: false,
      entityType: null,
      mft: 34,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: "0",
      negativeFlow: "0",
    },
    {
      tin: "HERMIONEE",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "HERMIONEE GRANGER",
      type: "1",
      flags: "0000000",
      isInitial: false,
      entityType: null,
      mft: 34,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "MALFOY",
      tinType: "2",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "MALFOY",
      type: "2",
      flags: "000000",
      isInitial: false,
      entityType: null,
      mft: 34,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: 0,
      negativeFlow: 0,
    },
  ],
  linkList: [
    {
      sourceId: "0HARRYPOTTER_201412",
      targetId: "1RONWEASLEY_201412",
      linkType: "K1",
      linkLabel: "0",
      negative: "false",
      thickness: "1",
      tinPerfection: "0",
      positiveFlow: "100000",
      negativeFlow: null,
      k1Count: null,
    },
    {
      sourceId: "0HARRYPOTTER_201412",
      targetId: "1HERMIONEE_201412",
      linkType: "K1",
      linkLabel: "0",
      negative: "false",
      thickness: "1",
      tinPerfection: "0",
      positiveFlow: "50000",
      negativeFlow: null,
      k1Count: null,
    },
    {
      sourceId: "0HARRYPOTTER_201412",
      targetId: "2MALFOY_201412",
      linkType: "K1",
      linkLabel: "0",
      negative: "false",
      thickness: "1",
      tinPerfection: "0",
      positiveFlow: "500",
      negativeFlow: null,
      k1Count: null,
    },
  ],
  allEntities: [
    "GROUP1__4",
    "GROUP2__4",
    "GROUP3__4",
    "HARRYPOTTER__0",
    "HARRYPOTTER__1",
    "RONWEASLEY__1",
    "GROUP4__4",
    "HERMIONEE__1",
    "MALFOY__2",
  ],
  allLinks: [
    "0HARRYPOTTER__1RONWEASLEY__CASE",
    "1HARRYPOTTER__GROUP1HARRYPOTTER_GROUP",
    "GROUP4HARRYPOTTER__2HARRYPOTTER__GROUP",
    "1HERMIONEE__2HARRYPOTTER__CASE",
    "2HARRYPOTTER__GROUP2HARRYPOTTER__GROUP",
    "2MALFOY__1RONWEASLEY__K1",
    "1HERMIONEE__GROUP3HERMIONEE__GROUP",
  ],
};
