export const getGraphFakeData = {
  entityList: [
    {
      //
      tin: "GROUP1_4_201412",
      tinType: "4",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "1 GROUP1",
      type: null,
      flags: null,
      isInitial: false,
      entityType: "GROUPOUT",
      mft: null,
      tpi: null,
      assets: null,
      linkTin: "HARRYPOTTER_201412",
      groupNode: true,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "GROUP2_4_201412",
      tinType: "4",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "2 GROUP2",
      type: null,
      flags: null,
      isInitial: false,
      entityType: "GROUPOUT",
      mft: null,
      tpi: null,
      assets: null,
      linkTin: "HARRYPOTTER_201412",
      groupNode: true,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "GROUP3_4_201412",
      tinType: "4",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "3 GROUP3",
      type: null,
      flags: null,
      isInitial: false,
      entityType: "GROUPOUT",
      mft: null,
      tpi: null,
      assets: null,
      linkTin: "HERMIONEE_201412",
      groupNode: true,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "GROUP4_4_201412",
      tinType: "4",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "4 GROUP4",
      type: null,
      flags: null,
      isInitial: false,
      entityType: "GROUPIN",
      mft: null,
      tpi: null,
      assets: null,
      linkTin: "2HARRYPOTTER_201412",
      groupNode: true,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "HARRYPOTTER",
      tinType: "0",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "Harry Potter",
      type: "0",
      flags: "0010101",
      isInitial: true,
      entityType: null,
      mft: 30,
      tpi: 453928,
      assets: "0",
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "HARRYPOTTER",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "Anonymous",
      type: "1",
      flags: "0000000",
      isInitial: true,
      entityType: null,
      mft: 2,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "HARRYPOTTERR",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "partnershp",
      type: "1",
      flags: "00001001",
      isInitial: true,
      entityType: null,
      mft: 65,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "HARRYPOTTERR",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "testing shapes",
      type: "1",
      flags: "00001001",
      isInitial: true,
      entityType: null,
      mft: 83,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "HARRYPOTTERRr",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "ANOTHERsuperlonglabelfortestingpurposes",
      type: "1",
      flags: "0000000",
      isInitial: true,
      entityType: null,
      mft: 67,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "HARRYPOTTERRR",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "OTHER - variant",
      type: "1",
      flags: "000000001",
      isInitial: true,
      entityType: null,
      mft: 99,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "HARRYPOTTER",
      tinType: "2",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "Harry Potter Inc",
      type: "2",
      flags: "0010000",
      isInitial: true,
      entityType: null,
      mft: 9,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: null,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "RONWEASLEY",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "RON WEASLEY",
      type: "1",
      flags: "0000000",
      isInitial: false,
      entityType: null,
      mft: 90,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "111222333",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "partnership",
      type: "1",
      flags: "0000000",
      isInitial: false,
      entityType: null,
      mft: 65,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "HERMIONEE",
      tinType: "1",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "HERMIONEE GRANGER",
      type: "1",
      flags: "0000000",
      isInitial: false,
      entityType: null,
      mft: 9,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      tin: "MALFOY",
      tinType: "2",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "MALFOY",
      type: "2",
      flags: "000000",
      isInitial: false,
      entityType: null,
      mft: 66,
      tpi: 0,
      assets: 0,
      linkTin: null,
      groupNode: false,
      positiveFlow: 152152,
      negativeFlow: -2532,
    },
    // {
    //   tin: "MALFOY1",
    //   tinType: "2",
    //   taxPeriod: "201412",
    //   isRealTaxPeriod: "true",
    //   name: "MALFOY",
    //   type: "2",
    //   flags: "000000",
    //   isInitial: false,
    //   entityType: null,
    //   mft: 66,
    //   tpi: 0,
    //   assets: 0,
    //   linkTin: null,
    //   groupNode: false,
    //   positiveFlow: 152152,
    //   negativeFlow: -2532,
    // },
    // {
    //   tin: "MALFOY2",
    //   tinType: "2",
    //   taxPeriod: "201412",
    //   isRealTaxPeriod: "true",
    //   name: "MALFOY",
    //   type: "2",
    //   flags: "000000",
    //   isInitial: false,
    //   entityType: null,
    //   mft: 66,
    //   tpi: 0,
    //   assets: 0,
    //   linkTin: null,
    //   groupNode: false,
    //   positiveFlow: 152152,
    //   negativeFlow: -2532,
    // },
    // {
    //   tin: "MALFOY3",
    //   tinType: "2",
    //   taxPeriod: "201412",
    //   isRealTaxPeriod: "true",
    //   name: "MALFOY",
    //   type: "2",
    //   flags: "000000",
    //   isInitial: false,
    //   entityType: null,
    //   mft: 66,
    //   tpi: 0,
    //   assets: 0,
    //   linkTin: null,
    //   groupNode: false,
    //   positiveFlow: 152152,
    //   negativeFlow: -2532,
    // },
    // {
    //   tin: "MALFOY4",
    //   tinType: "2",
    //   taxPeriod: "201412",
    //   isRealTaxPeriod: "true",
    //   name: "MALFOY",
    //   type: "2",
    //   flags: "000000",
    //   isInitial: false,
    //   entityType: null,
    //   mft: 66,
    //   tpi: 0,
    //   assets: 0,
    //   linkTin: null,
    //   groupNode: false,
    //   positiveFlow: 152152,
    //   negativeFlow: -2532,
    // },
    // {
    //   tin: "MALFOY5",
    //   tinType: "2",
    //   taxPeriod: "201412",
    //   isRealTaxPeriod: "true",
    //   name: "MALFOY",
    //   type: "2",
    //   flags: "000000",
    //   isInitial: false,
    //   entityType: null,
    //   mft: 66,
    //   tpi: 0,
    //   assets: 0,
    //   linkTin: null,
    //   groupNode: false,
    //   positiveFlow: 152152,
    //   negativeFlow: -2532,
    // },
    // {
    //   tin: "MALFOY6",
    //   tinType: "2",
    //   taxPeriod: "201412",
    //   isRealTaxPeriod: "true",
    //   name: "MALFOY",
    //   type: "2",
    //   flags: "000000",
    //   isInitial: false,
    //   entityType: null,
    //   mft: 66,
    //   tpi: 0,
    //   assets: 0,
    //   linkTin: null,
    //   groupNode: false,
    //   positiveFlow: 152152,
    //   negativeFlow: -2532,
    // },
    // {
    //   tin: "MALFOY7",
    //   tinType: "2",
    //   taxPeriod: "201412",
    //   isRealTaxPeriod: "true",
    //   name: "MALFOY",
    //   type: "2",
    //   flags: "000000",
    //   isInitial: false,
    //   entityType: null,
    //   mft: 66,
    //   tpi: 0,
    //   assets: 0,
    //   linkTin: null,
    //   groupNode: false,
    //   positiveFlow: 152152,
    //   negativeFlow: -2532,
    // },
    // {
    //   tin: "MALFOY8",
    //   tinType: "2",
    //   taxPeriod: "201412",
    //   isRealTaxPeriod: "true",
    //   name: "MALFOY",
    //   type: "2",
    //   flags: "000000",
    //   isInitial: false,
    //   entityType: null,
    //   mft: 66,
    //   tpi: 0,
    //   assets: 0,
    //   linkTin: null,
    //   groupNode: false,
    //   positiveFlow: 152152,
    //   negativeFlow: -2532,
    // },
    {
      //
      tin: "GROUP_TEST_1",
      tinType: "4",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "1 GROUP1",
      type: null,
      flags: null,
      isInitial: false,
      entityType: "GROUPOUT",
      mft: null,
      tpi: null,
      assets: null,
      linkTin: "HARRYPOTTER_201412",
      groupNode: true,
      positiveFlow: null,
      negativeFlow: null,
    },
    {
      //
      tin: "GROUP_TEST_2",
      tinType: "4",
      taxPeriod: "201412",
      isRealTaxPeriod: "true",
      name: "1 GROUP1",
      type: null,
      flags: null,
      isInitial: false,
      entityType: "GROUPOUT",
      mft: null,
      tpi: null,
      assets: null,
      linkTin: "HARRYPOTTER_201412",
      groupNode: true,
      positiveFlow: null,
      negativeFlow: null,
    },
  ],
  linkList: [
    {
      sourceId: "0HARRYPOTTER_201412",
      targetId: "1RONWEASLEY_201412",
      linkType: "CASE",
      linkLabel: "Case SSN",
      negative: "false",
      thickness: "1",
      tinPerfection: "0",
      positiveFlow: null,
      negativeFlow: null,
      k1Count: null,
    },
    {
      sourceId: "1RONWEASLEY_201412",
      targetId: "1RONWEASLEY_201412",
      linkType: "CASE",
      linkLabel: "Case SSN",
      negative: "false",
      thickness: "1",
      tinPerfection: "0",
      positiveFlow: null,
      negativeFlow: null,
      k1Count: null,
    },
    {
      sourceId: "1HARRYPOTTER_201412",
      targetId: "GROUP1_4_201412",
      linkType: "GROUP",
      linkLabel: null,
      negative: null,
      thickness: "1",
      tinPerfection: null,
      positiveFlow: null,
      negativeFlow: null,
      k1Count: null,
    },
    {
      sourceId: "GROUP4_4_201412",
      targetId: "2HARRYPOTTER_201412",
      linkType: "GROUP",
      linkLabel: null,
      negative: null,
      thickness: "1",
      tinPerfection: null,
      positiveFlow: null,
      negativeFlow: null,
      k1Count: null,
    },
    {
      sourceId: "1HERMIONEE_201412",
      targetId: "2HARRYPOTTER_201412",
      linkType: "CASE",
      linkLabel: "Case SSN",
      negative: "false",
      thickness: "10",
      tinPerfection: "0",
      positiveFlow: null,
      negativeFlow: null,
      k1Count: null,
    },
    {
      sourceId: "2HARRYPOTTER_201412",
      targetId: "GROUP2_4_201412",
      linkType: "GROUP",
      linkLabel: null,
      negative: null,
      thickness: "10",
      tinPerfection: null,
      positiveFlow: null,
      negativeFlow: null,
      k1Count: null,
    },
    {
      sourceId: "2MALFOY_201412",
      targetId: "1RONWEASLEY_201412",
      linkType: "K1",
      linkLabel: null,
      negative: "true",
      thickness: "10",
      tinPerfection: "0",
      positiveFlow: "152152",
      negativeFlow: "-2532",
      k1Count: "5",
    },
    {
      sourceId: "1HERMIONEE_201412",
      targetId: "GROUP3_4_201412",
      linkType: "GROUP",
      linkLabel: null,
      negative: null,
      thickness: "1",
      tinPerfection: null,
      positiveFlow: null,
      negativeFlow: null,
      k1Count: null,
    },
  ],
  allEntities: [
    "GROUP1__4",
    "GROUP2__4",
    "GROUP3__4",
    "HARRYPOTTER__0",
    "HARRYPOTTER__1",
    "RONWEASLEY__1",
    "GROUP4__4",
    "HERMIONEE__1",
    "MALFOY__2",
  ],
  allLinks: [
    "0HARRYPOTTER__1RONWEASLEY__CASE",
    "1HARRYPOTTER__GROUP1HARRYPOTTER_GROUP",
    "GROUP4HARRYPOTTER__2HARRYPOTTER__GROUP",
    "1HERMIONEE__2HARRYPOTTER__CASE",
    "2HARRYPOTTER__GROUP2HARRYPOTTER__GROUP",
    "2MALFOY__1RONWEASLEY__K1",
    "1HERMIONEE__GROUP3HERMIONEE__GROUP",
  ],
};
