import React, { Component } from "react";
import YK1 from "../../js/yk1/yk1";
import cytoscape from "cytoscape";

class LegendTab extends Component {
  componentDidMount() {
    let cyto = cytoscape({
      container: document.getElementById("legendCy"),

      boxSelectionEnabled: false,
      autounselectify: true,
      autolock: true,
      userZoomingEnabled: false,
      userPanningEnabled: false,

      style: [
        {
          selector: "node",
          css: {
            content: "data(label)",
            "background-color": "data(backgroundColor)",
            width: "data(width)",
            height: 35,
            shape: "data(shape)",
            "shape-polygon-points": "data(poly)",
            "text-valign": "center",
            "text-halign": "center",
            color: "data(contentColor)",
            "text-wrap": "wrap",
            "border-width": "data(borderWidth)",
            "border-color": "data(borderColor)",
            "font-size": "11.5px",
          },
        },
        {
          selector: "edge",
          css: {
            width: "data(width)",
            "target-arrow-shape": "triangle",
            "line-color": "data(lineColor)",
            "line-style": "data(lineStyle)",
            "target-arrow-color": "data(target-arrow-color)",
            label: "data(label)",
            color: "data(color)",
            "source-text-offset": "7",
            "curve-style": "unbundled-bezier",
            "control-point-distance": "35px",
            "control-point-weight": "0.64",
            "text-margin-y": 12,
            "text-margin-x": -12,
          },
        },
      ],

      elements: {
        nodes: [
          {
            data: {
              id: "node1065",
              parent: "parentNode1065",
              label: "1065",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 0, y: 50 },
          },
          {
            data: {
              id: "node1065Desc",
              label: "Partnership",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: 0,
              borderColor: "#FFFFFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 50 },
          },

          {
            data: {
              id: "node1041",
              label: "1041",
              shape: "diamond",
              poly: "0 0",
              height: 50,
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 0, y: 100 },
          },
          {
            data: {
              id: "node1041Desc",
              label: "Trust",
              shape: "diamond",
              poly: "0 0",
              height: 50,
              backgroundColor: "#FFFFFF",
              borderWidth: 0,
              borderColor: "#FFFFFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 100 },
          },

          {
            data: {
              id: "node1120",
              label: "1120",
              shape: "polygon",
              poly: YK1.trapezoidBottomHeavy,
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 0, y: 150 },
          },
          {
            data: {
              id: "node1120Desc",
              label: "Corporation",
              shape: "polygon",
              poly: YK1.trapezoidBottomHeavy,
              backgroundColor: "#FFFFFF",
              borderWidth: 0,
              borderColor: "#FFFFFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 150 },
          },

          {
            data: {
              id: "node1120S",
              label: "1120S",
              shape: "rectangle",
              poly: "0 0",
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 0, y: 200 },
          },
          {
            data: {
              id: "node1120SDesc",
              label: "S Corporation",
              shape: "rectangle",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: 0,
              borderColor: "#FFFFFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 200 },
          },

          {
            data: {
              id: "nodeOther1120",
              label: "Other 1120",
              shape: "hexagon",
              poly: "0 0",
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 100,
              contentColor: "#000",
            },
            position: { x: 0, y: 250 },
          },
          {
            data: {
              id: "nodeOther1120Desc",
              label: "1120 Variant\n(e.g. 1120 REIT)",
              shape: "hexagon",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: 0,
              borderColor: "#FFFFFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 250 },
          },

          {
            data: {
              id: "nodeTEGE",
              label: "TEGE",
              shape: "polygon",
              poly: YK1.trapezoidTopHeavy,
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 0, y: 300 },
          },
          {
            data: {
              id: "nodeTEGEDesc",
              label: "Form\n990 or 5227",
              shape: "polygon",
              poly: YK1.trapezoidTopHeavy,
              backgroundColor: "#FFFFFF",
              borderWidth: 0,
              borderColor: "#FFFFFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 300 },
          },

          {
            data: {
              id: "node1040",
              label: "1040",
              shape: "roundrectangle",
              poly: "0 0",
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 0, y: 350 },
          },
          {
            data: {
              id: "node1040Desc",
              label: "Individual",
              shape: "roundrectangle",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 350 },
          },

          {
            data: {
              id: "nodeUnknown",
              label: "???",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 0, y: 400 },
          },
          {
            data: {
              id: "nodeUnknownDesc",
              label: "Unknown",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 400 },
          },

          {
            data: {
              id: "nodeGroup",
              label: "Group Node",
              shape: "octagon",
              poly: "0 0",
              backgroundColor: YK1.FILLCOLOR_GROUP,
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 100,
              contentColor: "#000",
            },
            position: { x: 0, y: 475 },
          },
          {
            data: {
              id: "nodeGroupDesc",
              label: "Payees, Payers,\nSubs, etc",
              shape: "octagon",
              poly: "0 0",
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 150, y: 475 },
          },
          // ========
          {
            data: {
              id: "nodeForeign",
              label: "Purple",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: YK1.FILLCOLOR_FOREIGN,
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              contentColor: "#FFF",
              width: 100,
            },
            position: { x: 400, y: 50 },
          },
          {
            data: {
              id: "nodeForeignDesc",
              label: "Foreign Address",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 550, y: 50 },
          },

          {
            data: {
              id: "nodeITIN",
              label: "Green",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: YK1.FILLCOLOR_ITIN,
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 100,
              contentColor: "#000",
            },
            position: { x: 400, y: 100 },
          },
          {
            data: {
              id: "nodeITINDesc",
              label: "ITIN",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 550, y: 100 },
          },

          {
            data: {
              id: "nodeHaven",
              label: "Black",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: YK1.FILLCOLOR_HAVEN,
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: YK1.LINECOLOR_HAVEN,
              width: 100,
              contentColor: "#FFF",
            },
            position: { x: 400, y: 150 },
          },
          {
            data: {
              id: "nodeHavenDesc",
              label: "Haven",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: YK1.LINECOLOR_HAVEN,
              width: 90,
              contentColor: "#000",
            },
            position: { x: 550, y: 150 },
          },

          {
            data: {
              id: "nodeIrtfTpi",
              label: "Red",
              shape: "roundrectangle",
              poly: "0 0",
              backgroundColor: YK1.FILLCOLOR_HIGHTPI,
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 400, y: 200 },
          },
          {
            data: {
              id: "nodeIrtfTpiDesc",
              label: "IRTF-TPI\n> $250,000",
              shape: "roundrectangle",
              poly: "0 0",
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 550, y: 200 },
          },

          {
            data: {
              id: "nodeBrtfHighAssets",
              label: "Orange",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: YK1.FILLCOLOR_HIGHASSETS,
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 400, y: 250 },
          },
          {
            data: {
              id: "nodeBrtfHighAssetsDesc",
              label: "BRTF-Total Assets\n> $10,000,000",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 550, y: 250 },
          },

          {
            data: {
              id: "nodeShelter",
              label: "Yellow",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: YK1.FILLCOLOR_SHELTER,
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 100,
              contentColor: "#000",
            },
            position: { x: 400, y: 300 },
          },
          {
            data: {
              id: "nodeShelterDesc",
              label: "Shelter",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 550, y: 300 },
          },

          {
            data: {
              id: "nodeInitialTin",
              label: "Bold Border",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.INITIAL_NODE_BORDER_THICKNESS,
              borderColor: "#000000",
              width: 100,
              contentColor: "#000",
            },
            position: { x: 400, y: 375 },
          },
          {
            data: {
              id: "nodeInitialTinDesc",
              label: "Initial TIN",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 550, y: 375 },
          },

          {
            data: {
              id: "nodeForm5500Filed",
              label: "Blue Border",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#D3D3D3",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#0000FF",
              width: 100,
              contentColor: "#000",
            },
            position: { x: 400, y: 425 },
          },
          {
            data: {
              id: "nodeForm5500FiledDesc",
              label: "Form 5500 Filed",
              shape: "polygon",
              poly: YK1.rhomboidReverse,
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 550, y: 425 },
          },
          {
            data: {
              id: "k2",
            },
            style: {
              backgroundImage: "k2.png",
              backgroundColor: "white",
              borderColor: "white",
              shape: "square",
              backgroundHeight: 25,
              backgroundWidth: 35,
              height: 50,
              width: 50,
            },
            position: { x: 400, y: 480 },
          },
          {
            data: {
              id: "k2Desc",
              label: "k2 Indicator",
              // shape: "ellipse",
              height: 50,
              width: 50,
              poly: "0 0",
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              contentColor: "#000",
            },
            position: { x: 550, y: 480 },
          },
          // =====
          {
            data: {
              id: "nodeAddress",
            },
            position: { x: 800, y: 60 },
            style: {
              backgroundImage: "building.png",
              backgroundColor: "white",
              borderColor: "white",
              shape: "square",
              backgroundHeight: 50,
              backgroundWidth: 50,
              height: 50,
              width: 50,
            },
          },
          {
            data: {
              id: "nodeAddressDesc",
              label: "Address",
              shape: "triangle",
              poly: "0 0",
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              width: 90,
              contentColor: "#000",
            },
            position: { x: 950, y: 50 },
          },

          {
            data: {
              id: "nodePreparer",
            },
            style: {
              backgroundImage: "person.png",
              backgroundColor: "white",
              borderColor: "white",
              shape: "square",
              backgroundHeight: 50,
              backgroundWidth: 50,
              height: 50,
              width: 50,
            },
            position: { x: 800, y: 125 },
          },
          {
            data: {
              id: "nodePreparerDesc",
              label: "Preparer",
              shape: "ellipse",
              height: 50,
              width: 50,
              poly: "0 0",
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              contentColor: "#000",
            },
            position: { x: 950, y: 125 },
          },
          {
            data: {
              id: "orbisIndicator",
            },
            style: {
              backgroundImage: "redFlag.png",
              backgroundColor: "white",
              borderColor: "white",
              shape: "square",
              backgroundHeight: 50,
              backgroundWidth: 50,
              height: 50,
              width: 50,
            },
            position: { x: 800, y: 190 },
          },
          {
            data: {
              id: "orbisIndicatorDesc",
              label: "ORBIS Data Indicator",
              shape: "ellipse",
              height: 50,
              width: 50,
              poly: "0 0",
              backgroundColor: "#FFF",
              borderWidth: 0,
              borderColor: "#FFF",
              contentColor: "#000",
            },
            position: { x: 950, y: 190 },
          },

          // positive flow, invisible nodes
          {
            data: {
              id: "positiveFlowSource",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 750, y: 230 },
          },
          {
            data: {
              id: "positiveFlowTarget",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 975, y: 230 },
          },
          // negative flow, invisible nodes
          {
            data: {
              id: "negativeFlowSource",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 750, y: 260 },
          },
          {
            data: {
              id: "negativeFlowTarget",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 975, y: 260 },
          },
          // parent/sub link, invisible nodes
          {
            data: {
              id: "parentSubSource",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 750, y: 290 },
          },
          {
            data: {
              id: "parentSubTarget",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 975, y: 290 },
          },
          // Case SSN link, invisible nodes
          {
            data: {
              id: "caseSsnSource",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 750, y: 320 },
          },
          {
            data: {
              id: "caseSsnTarget",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 975, y: 320 },
          },
          // Group link, invisible nodes
          {
            data: {
              id: "groupSource",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 750, y: 350 },
          },
          {
            data: {
              id: "groupTarget",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 975, y: 350 },
          },
          // address/preparer link, invisible nodes
          {
            data: {
              id: "addressPreparerSource",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 750, y: 380 },
          },
          {
            data: {
              id: "addressPreparerTarget",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 975, y: 380 },
          },
          // TIN perfection link, invisible nodes
          {
            data: {
              id: "tinPerfectionSource",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 750, y: 430 },
          },
          {
            data: {
              id: "tinPerfectionTarget",
              label: "",
              shape: "ellipse",
              poly: "0 0",
              backgroundColor: "#FFFFFF",
              borderWidth: YK1.DEFAULT_NODE_BORDER_THICKNESS,
              borderColor: "#FFFFFF",
              width: 1,
              contentColor: "#000",
            },
            position: { x: 975, y: 430 },
          },
        ],

        edges: [
          {
            data: {
              id: "edgePositiveFlow",
              label: "Positive Flow",
              source: "positiveFlowSource",
              target: "positiveFlowTarget",
              width: "1",
              lineColor: "#000000",
              lineStyle: "solid",
              "target-arrow-color": "#000000",
              color: "#000000",
              "source-text-offset": "7",
            },
          },
          {
            data: {
              id: "edgeNegativeFlow",
              label: "Negative Flow",
              source: "negativeFlowSource",
              target: "negativeFlowTarget",
              width: "1",
              lineColor: YK1.LINK_COLOR_NEGATIVE,
              lineStyle: "solid",
              "target-arrow-color": YK1.LINK_COLOR_NEGATIVE,
              color: YK1.LINK_COLOR_NEGATIVE,
              "source-text-offset": "7",
            },
          },
          {
            data: {
              id: "parentSubLink",
              label: "Parent/Sub",
              source: "parentSubSource",
              target: "parentSubTarget",
              width: "1",
              lineColor: YK1.LINK_COLOR_PARENT,
              lineStyle: "solid",
              "target-arrow-color": YK1.LINK_COLOR_PARENT,
              color: YK1.LINK_COLOR_PARENT,
              "source-text-offset": "7",
            },
          },
          {
            data: {
              id: "caseSsnLink",
              label: "Case SSN",
              source: "caseSsnSource",
              target: "caseSsnTarget",
              width: "1",
              lineColor: YK1.LINK_COLOR_CASE,
              lineStyle: "solid",
              "target-arrow-color": YK1.LINK_COLOR_CASE,
              color: YK1.LINK_COLOR_CASE,
              "source-text-offset": "7",
            },
          },
          {
            data: {
              id: "groupLink",
              label: "Group",
              source: "groupSource",
              target: "groupTarget",
              width: "1",
              lineColor: YK1.LINK_COLOR_GROUP,
              lineStyle: "solid",
              "target-arrow-color": YK1.LINK_COLOR_GROUP,
              color: YK1.LINK_COLOR_GROUP,
              "source-text-offset": "7",
            },
          },
          {
            data: {
              id: "addressPreparerLink",
              label: "Address or Preparer Link",
              source: "addressPreparerSource",
              target: "addressPreparerTarget",
              width: "1",
              lineColor: "#000000",
              lineStyle: "dotted",
              "target-arrow-color": "#000000",
              color: "#000000",
              "source-text-offset": "7",
            },
          },
          {
            data: {
              id: "tinPerfectionLink",
              label: "Probable link based on TIN Perfection",
              source: "tinPerfectionSource",
              target: "tinPerfectionTarget",
              width: "1",
              lineColor: "#000000",
              lineStyle: "dashed",
              "target-arrow-color": "#000000",
              color: "#000000",
              "source-text-offset": "7",
            },
          },
        ],
      },

      layout: {
        name: "preset",
        padding: 5,
      },
    });
    this.props.loadCurrentCyto(cyto);
  }
  render() {
    return (
      <div
        id="legendCy"
        style={{
          height: window.innerHeight - 120,
          width: window.innerWidth - 50,
        }}
      />
    );
  }
}

export default LegendTab;
