/**
 *
 */

const K1Constants = function(Y) {
  Y.nodeLocationHelper = { x: 0, y: 0 };
  Y.DELIMITER = "\t";
  Y.DELIMITER_COMMA = ",";
  // prefixes for some of the display elements
  Y.DIV_PREFIX = "cy";
  Y.DIV_COMPARE_PREFIX = "compare";

  // Tin Types
  Y.TIN_TYPE_SSN = "0";
  Y.TIN_TYPE_INVALID = "1";
  Y.TIN_TYPE_EIN = "2";
  Y.TIN_TYPE_K1EIN = "3";
  Y.TIN_TYPE_GROUP = "4";
  Y.TIN_TYPE_UNKNOWN = "5";
  Y.TIN_TYPE_ADDRESS = "6";
  Y.TIN_TYPE_PREPARER = "7";

  Y.TIN_TYPE_ID = [];
  Y.TIN_TYPE_ID[0] = "SSN";
  Y.TIN_TYPE_ID[1] = "INVALID";
  Y.TIN_TYPE_ID[2] = "EIN";
  Y.TIN_TYPE_ID[5] = "UNKNOWN";

  Y.NODE_TYPE_ADDRESS = "ADDRESS";
  Y.NODE_TYPE_PREPARER = "PREPARER";
  Y.NODE_TYPE_GROUP = "GROUP";
  Y.NODE_TYPE_NODE = "NODE";

  //MFT mappings
  Y.MFT_1120 = 2;
  Y.MFT_1040 = 30;
  Y.MFT_1065 = 65;
  Y.MFT_1041 = 66;
  Y.MFT_1120S = 67;
  Y.MFT_1120V = 99;
  Y.MFT_990EZ = 9;
  Y.MFT_990 = 90;
  Y.MFT_5227 = 83;
  Y.MFT_UNKNOWN = -1;

  // Link type
  Y.LINK_TYPE_K1 = "K1";
  Y.LINK_TYPE_PARENT = "PARENT";
  Y.LINK_TYPE_GROUP = "GROUP";
  Y.LINK_TYPE_CASE = "CASE";
  Y.LINK_TYPE_ADDRESS = "ADDRESS";
  Y.LINK_TYPE_PREPARER = "PREPARER";

  Y.GROUP_NODE_TYPE_PAYER = "Payers";
  Y.GROUP_NODE_TYPE_PAYEE = "Payees";
  Y.GROUP_NODE_TYPE_PARENT = "Parents";
  // Y.GROUP_NODE_TYPE_SUB = "Subsidiaries";
  // Y.GROUP_NODE_TYPE_CASESSN = "SSNs";
  Y.GROUP_NODE_TYPE_ADDRESS = "Addresses";
  Y.GROUP_NODE_TYPE_PREPARER = "Preparers";
  Y.GROUP_NODE_TYPE_SUB = "SUBSIDIARY";
  Y.GROUP_NODE_TYPE_CASESSN = "CASESSN";

  // from K1Constants.initializeConstant()
  Y.GROUP_DETAIL = [];
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PAYER + "TITLE"] = "Payers";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PAYEE + "TITLE"] = "Payees";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PARENT + "TITLE"] = "Parents";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_SUB + "TITLE"] = "Subsidiaries";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_CASESSN + "TITLE"] = "Case SSNs";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_ADDRESS + "TITLE"] = "Addresses";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PREPARER + "TITLE"] = "Preparers";

  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PAYER + "TIN"] = "Payer TIN";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PAYEE + "TIN"] = "Payee TIN";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PARENT + "TIN"] = "Parent EIN";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_SUB + "TIN"] = "Sub EIN";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_CASESSN + "TIN"] = "Payee TIN";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_ADDRESS + "TIN"] = "TIN";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PREPARER + "TIN"] = "TIN";

  //Initialize GROUP_DETAIL_TIN_TYPE_COLUMNS
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PAYER + "TINTYPE"] = "Payer TIN Type";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PAYEE + "TINTYPE"] = "Payee TIN Type";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PARENT + "TINTYPE"] = "Parent EIN";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_SUB + "TINTYPE"] = "Sub EIN";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_CASESSN + "TINTYPE"] = "Payee TIN Type";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_ADDRESS + "TINTYPE"] = "TIN Type";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PREPARER + "TINTYPE"] = "TIN Type";

  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PAYER + "KEY"] = "0";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PAYEE + "KEY"] = "1";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PARENT + "KEY"] = "2";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_SUB + "KEY"] = "3";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_CASESSN + "KEY"] = "4";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_ADDRESS + "KEY"] = "5";
  Y.GROUP_DETAIL[Y.GROUP_NODE_TYPE_PREPARER + "KEY"] = "6";

  //Node processing constants
  Y.HIGH_ASSET_LIMIT = 10000000;
  Y.HIGH_TPI_LIMIT = 250000;

  //Node constants
  Y.DEFAULT_NODE_BORDER_THICKNESS = 2;
  Y.INITIAL_NODE_BORDER_THICKNESS = 5;
  Y.GROUP_NODE_BORDER_THICKNESS = 1;

  //Colors
  Y.BLACK = "#000000";
  Y.BLUE = "#0000FF";
  Y.BR_LIGHTGRAY = "#EAEAEA";
  Y.DARKGRAY = "#828282";
  Y.GREEN = "#00cd00";
  Y.LIGHTGRAY = "#D3D3D3";
  Y.ORANGE = "#FF8000";
  Y.RED = "#FF0000";
  Y.WHITE = "#FFFFFF";
  Y.YELLOW = "#FFFF00";
  Y.LIGHTBLUE = "#BEE1FF";
  Y.PURPLE = "#9E7BFF";

  Y.TEXTCOLOR_DEFAULT = Y.BLACK;
  Y.LINECOLOR_5500 = Y.BLUE;
  Y.LINECOLOR_HAVEN = Y.LIGHTGRAY;

  Y.FILLCOLOR_FOREIGN = Y.PURPLE;
  Y.FILLCOLOR_ITIN = Y.GREEN;
  Y.FILLCOLOR_HAVEN = Y.BLACK;
  Y.FILLCOLOR_HIGHASSETS = Y.ORANGE;
  Y.FILLCOLOR_HIGHTPI = Y.RED;
  Y.FILLCOLOR_SHELTER = Y.YELLOW;
  Y.FILLCOLOR_GROUP = Y.LIGHTBLUE;
  Y.FILLCOLOR_ADDRESS = Y.WHITE;
  Y.FILLCOLOR_PREPARER = Y.WHITE;

  Y.LINK_COLOR_NEGATIVE = Y.RED;
  Y.LINK_COLOR_PARENT = Y.GREEN;
  Y.LINK_COLOR_CASE = Y.ORANGE;
  Y.LINK_COLOR_GROUP = Y.BLUE;

  return Y;
};

export default K1Constants;
